kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-fleet-2
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume-fleet-2
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume-fleet-2
      persistentVolumeClaim:
        claimName: csi-pvc-fleet-2 # defined in csi-pvc.yaml

