kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/abhideodhar-coder/fleet-examples 
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m 
  # user must properly provide a secret that have write access to git repository
  #clientSecretName: secret 
  # specify the commit pattern
  imageScanCommit:
    authorName: adeodhar
    authorEmail: adeodhar@netapp.com
    messageTemplate: "update image"
