kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-fleet-3
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume-fleet-3
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume-fleet-3
      persistentVolumeClaim:
        claimName: csi-pvc-fleet-3 # defined in csi-pvc.yaml

