kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simple
  namespace: allclusters
spec:
  repo: https://github.com/abhideodhar-coder/fleet-examples
  paths:
  - csi
targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: equinix
